name: free_rider
description: 매일 무료로, 당당하게 - 대한민국 교통비 제로 플랫폼
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  
  # Navigation
  go_router: ^12.0.0
  
  # UI/UX
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.0
  gap: ^3.0.1
  
  # Native Features
  flutter_native_splash: ^2.3.0
  flutter_local_notifications: ^16.0.0
  vibration: ^1.8.0
  flutter_nfc_kit: ^3.3.1
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  
  # Sensors
  sensors_plus: ^4.0.0
  pedometer: ^4.0.1
  
  # Network & API
  dio: ^5.4.0
  retrofit: ^4.0.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Storage
  shared_preferences: ^2.2.0
  
  # QR & Sharing
  mobile_scanner: ^3.5.0
  share_plus: ^7.2.0
  flutter_secure_storage: ^9.0.0
  hive_flutter: ^1.1.0
  
  # Utilities
  intl: ^0.18.1
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.2.0
  package_info_plus: ^5.0.0
  device_info_plus: ^9.1.0
  connectivity_plus: ^5.0.0
  
  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_messaging: ^14.7.0
  firebase_analytics: ^10.7.0
  firebase_crashlytics: ^3.4.0
  
  # Social Login
  kakao_flutter_sdk: ^1.9.0
  sign_in_with_apple: ^5.0.0
  
  # Camera & QR
  camera: ^0.10.5
  qr_code_scanner: ^1.0.1
  image_picker: ^1.0.0
  
  # Charts & Visualizations
  fl_chart: ^0.65.0
  
  # WebSocket
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  retrofit_generator: ^8.0.0
  json_serializable: ^6.7.0
  freezed: ^2.4.0
  riverpod_generator: ^2.3.0
  hive_generator: ^2.0.0
  mockito: ^5.4.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  # Fonts
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900

flutter_native_splash:
  color: "#00FF88"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"